# Generated by Django 2.2.2 on 2020-03-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateField(auto_now=True, verbose_name='last login'),
        ),
    ]
